<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.apache.hop</groupId>
        <artifactId>hop-plugins-transforms</artifactId>
        <version>2.16.0-SNAPSHOT</version>
    </parent>
    <artifactId>hop-transform-rapidstart</artifactId>
    <packaging>jar</packaging>
    <name>Plugin Hop transform rapidstart MSD365/BC</name>
    <description>Vytvorí XML podla rapidstart</description>
    <dependencies>
        <dependency>
            <groupId>org.apache.hop</groupId>
            <artifactId>hop-transform-rowgenerator</artifactId>
            <version>2.16.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
